### ISSUE TITLE
AttributeError: module 'pytorch_metric_learning.losses' has no attribute 'MINDSSC'

### ISSUE THREAD

**Issue by tphankr** [multimodallearning/convexAdam#1]
Thank you for your code.
Please me ask about which "pytorch_metric_learning.losses" version did you use or how do we solution this problem? Because I faced the error when type " python  l2r_2021_convexAdam_task2_docker.py " 
![image](https://user-images.githubusercontent.com/37217354/146056872-97d6eecb-3412-4b73-8207-bf278b05f5ec.png)

![image](https://user-images.githubusercontent.com/37217354/146057807-fa9ed8a8-52aa-4728-adeb-3526f260ffa9.png)

I also used:
+  pip install pytorch_metric_learning==1.0.0 or 0.9.99 or 0.9.98 but all had the above error.

Thank you.

**Comment by mattiaspaul** [comment]
You need to include our MIND-Loss function from our voxelmorph fork https://github.com/multimodallearning/voxelmorph/blob/389274436263ef0cd9a32a566f12bf7f048f6843/pytorch/losses.py#L106
in the next version we'll directly include this code

**Comment by tphankr** [comment]
Thank you @mattiaspaul, I fixed that error.
Allows me ask something more. I am wondering, has the training processing in your code? Normolly in my limit knowlege, the first we must to do training step to have the checkpoint and then do the test step.

My status:
With your code, I typed "python l2r_2021_convexAdam_task2_docker.py" and we have extremely the results, as following: 
![image](https://user-images.githubusercontent.com/37217354/146113687-5f5bd229-142d-4dd3-a1d4-dd120311f803.png)

When do we the train dataset? 
![image](https://user-images.githubusercontent.com/37217354/146113786-8777b82b-5f9e-4452-98be-a8aa6f941f4e.png)
![image](https://user-images.githubusercontent.com/37217354/146113839-29cc3b8b-c379-41bc-89f8-e85df6d9f78f.png)

Thank you very much @mattiaspaul .

**Comment by thatwyj** [comment]
@tphankr hey，I am a beginner and I want to reproduce this code, but after reading the paper, I don't know what to do. Can you leave an email address to help me

**Comment by Atoposiii** [comment]
@tphankr I also encountered the same problem, have you solved this problem?

**Comment by chrgrbr** [comment]
We have updated our codebase: You can find the MIND computation here:
https://github.com/multimodallearning/convexAdam/blob/980a450758e8621a41b07c4d259910dae3f58118/src/convexAdam/convex_adam_MIND.py#L22C5-L22C6

Please do not hesitate to open another issue if needed!
