### ISSUE TITLE
How to get the file "cases.csv"

### ISSUE THREAD

**Issue by Jerry1070** [multimodallearning/convexAdam#5]
Hi, I want to run this code for the Task1 in Learn2reg 2021, but I don't have the file "cases.csv", could you please provide it to me. In addition, could I know where I can get the final warped moving image?

**Comment by huaibovip** [comment]
Can you provide the preprocessed AbdomenMRCT dataset and cases.csv?

**Comment by chrgrbr** [comment]
Sorry for the late reply: You can find all L2R datasets over at https://learn2reg.grand-challenge.org/
